export const SUPPORTED_LANGUAGES = ['pt-BR', 'en'] as const;

export type SupportedLanguage = (typeof SUPPORTED_LANGUAGES)[number];

export const DEFAULT_LANGUAGE: SupportedLanguage = 'en';

export const localizationResources = {
  en: {
    translation: {
      app: {
        readyBody: 'Router, SQLite, and preferences are initialized.',
        readyTitle: 'Expo foundation ready',
        loading: 'Loading app shell…',
        error: 'Unable to start the app shell.',
        designPreviewBody: 'Semantic tokens, adapters, and theme resolution are wired up.',
        designPreviewTitle: 'Design system preview',
      },
      feedback: {
        undo: 'Undo',
        undoHint: 'Restore the removed item.',
      },
      home: {
        activeSummaryBody: 'Open lists keep moving until they are finalized.',
        activeSummaryBudgetLabel: 'Budget',
        activeSummaryTitle: 'Active summaries',
        activeSummaryListsLabel: 'Lists',
        editList: 'Edit',
        finalizedSummaryBody: 'Finished lists stay readable and can be reopened later.',
        finalizedSummaryBudgetLabel: 'Budget',
        finalizedSummaryListsLabel: 'Lists',
        finalizedSummaryTitle: 'Finalized summaries',
        loadList: 'Load',
        reopenList: 'Reopen',
        listStatusDraft: 'Draft',
        listStatusFinalized: 'Finalized',
        listStatusActive: 'Active',
        emptyAction: 'Create list',
        emptyBody: 'No saved lists yet. Start a new plan to track a budget.',
        emptyTitle: 'Nothing to review yet',
        subtitle: 'Plan the next list offline before you shop.',
        title: 'Home',
        openCreateList: 'Create list',
        openCreateListHint: 'Open the list shell to choose a currency and start planning.',
      },
      listDetail: {
        addItem: 'Add item',
        addItemHint: 'Open the planned-item editor to add another item to the list.',
        actualPriceLabel: 'Actual price per {{unit}}',
        finalizeHint: 'Finalize this list when the items are ready.',
        finalizeLabel: 'Finalize list',
        reopenHint: 'Reopen the finalized list so it can be edited again.',
        reopenLabel: 'Reopen list',
        removedItemMessage: 'Removed {{name}}. Undo?',
        removeItemHint: 'Soft-remove this item and keep it available for immediate undo.',
        title: 'List details',
      },
      createList: {
        addItem: 'Add planned item',
        addItemHint: 'Open the planned-item editor to add one item to the draft.',
        budgetHint: 'Use localized currency formatting for this shell.',
        budgetLabel: 'Budget',
        budgetPlaceholder: '$40.00',
        close: 'Close',
        clearItems: 'Clear items',
        clearItemsHint: 'Removes the planned items from the shell.',
        currencyHint: 'Currency can change until the first item exists.',
        currencyLabel: 'Currency',
        currencyLockedHint: 'Currency is locked after the first item exists.',
        closeHint: 'Dismiss the list shell without saving.',
        finalize: 'Finalize list',
        finalizeHint: 'Disabled until the list has a name, budget, and at least one planned item.',
        itemCount: '{{count}} planned items added',
        itemsLabel: 'Planned items',
        itemsHint: 'Save and finalize need a name, a budget, and at least one planned item.',
        nameHint: 'Give the list a clear name.',
        nameLabel: 'List name',
        namePlaceholder: 'Weekly groceries',
        save: 'Save draft',
        saveHint: 'Disabled until the list has a name, budget, and at least one planned item.',
        summaryBudgetLabel: 'Budget preview',
        summaryCurrencyLabel: 'Draft currency',
        summaryItemsLabel: 'Planned items',
        summaryTitle: 'Current draft',
        title: 'Create list',
      },
      plannedItem: {
        close: 'Close',
        editTitle: 'Edit planned item',
        edit: 'Edit item',
        errors: {
          ambiguous: 'Use one locale separator only.',
          empty: 'Enter a value.',
          invalid: 'Use a valid localized number.',
          nonPositive: 'Value must be greater than zero.',
          precision: 'Too many decimal places for this unit.',
          unsafe: 'Value is too large.',
        },
        nameHint: 'Use the product name only.',
        nameLabel: 'Item name',
        namePlaceholder: 'Potatoes',
        priceHint: 'Enter a localized price per selected unit.',
        priceLabel: 'Planned price per {{unit}}',
        quantityHintFractional: 'Up to 3 decimals for this unit.',
        quantityHintWhole: 'Whole numbers only for this unit.',
        quantityLabel: 'Quantity',
        save: 'Save item',
        saveEdit: 'Save changes',
        remove: 'Remove item',
        title: 'Planned item',
        unitHint: 'Use only piece, pack, kg, g, l, or ml.',
        unitLabel: 'Unit',
      },
      units: {
        g: 'g',
        kg: 'kg',
        l: 'l',
        ml: 'ml',
        pack: 'pack',
        piece: 'piece',
      },
      form: {
        currencyLabel: 'Currency',
        searchHelper: 'Styled by semantic tokens, not screen colors.',
        searchLabel: 'Search',
        searchPlaceholder: 'Budget groceries',
        openSheet: 'Open sheet',
      },
      preferences: {
        currencyBrl: 'Brazilian real',
        currencySystem: 'System',
        currencyUsd: 'US dollar',
        languageSystem: 'System',
      },
    },
  },
  'pt-BR': {
    translation: {
      app: {
        readyBody: 'Router, SQLite e preferências estão inicializados.',
        readyTitle: 'Base do Expo pronta',
        loading: 'Carregando a base do app…',
        error: 'Não foi possível iniciar a base do app.',
        designPreviewBody: 'Tokens semânticos, adapters e resolução de tema já estão conectados.',
        designPreviewTitle: 'Prévia do design system',
      },
      feedback: {
        undo: 'Desfazer',
        undoHint: 'Restaura o item removido.',
      },
      home: {
        activeSummaryBody: 'Listas abertas seguem em movimento até serem finalizadas.',
        activeSummaryBudgetLabel: 'Orçamento',
        activeSummaryTitle: 'Resumos ativos',
        activeSummaryListsLabel: 'Listas',
        editList: 'Editar',
        finalizedSummaryBody: 'Listas finalizadas continuam legíveis e podem ser reabertas depois.',
        finalizedSummaryBudgetLabel: 'Orçamento',
        finalizedSummaryListsLabel: 'Listas',
        finalizedSummaryTitle: 'Resumos finalizados',
        loadList: 'Carregar',
        reopenList: 'Reabrir',
        listStatusDraft: 'Rascunho',
        listStatusFinalized: 'Finalizada',
        listStatusActive: 'Ativa',
        emptyAction: 'Criar lista',
        emptyBody: 'Ainda não há listas salvas. Comece um novo plano para acompanhar um orçamento.',
        emptyTitle: 'Nada para revisar ainda',
        subtitle: 'Planeje a próxima lista offline antes de comprar.',
        title: 'Início',
        openCreateList: 'Criar lista',
        openCreateListHint: 'Abre a base da lista para escolher a moeda e começar o planejamento.',
      },
      listDetail: {
        addItem: 'Adicionar item',
        addItemHint: 'Abre o editor de item planejado para adicionar outro item à lista.',
        actualPriceLabel: 'Preço real por {{unit}}',
        finalizeHint: 'Finalize esta lista quando os itens estiverem prontos.',
        finalizeLabel: 'Finalizar lista',
        reopenHint: 'Reabre a lista finalizada para que ela possa ser editada novamente.',
        reopenLabel: 'Reabrir lista',
        removedItemMessage: 'Removido(a) {{name}}. Desfazer?',
        removeItemHint: 'Remove o item de forma suave e mantém o desfazer imediato.',
        title: 'Detalhes da lista',
      },
      createList: {
        addItem: 'Adicionar item planejado',
        addItemHint: 'Abre o editor de item planejado para adicionar um item ao rascunho.',
        budgetHint: 'Use a formatação local da moeda neste shell.',
        budgetLabel: 'Orçamento',
        budgetPlaceholder: 'R$ 40,00',
        close: 'Fechar',
        clearItems: 'Limpar itens',
        clearItemsHint: 'Remove os itens planejados da base.',
        currencyHint: 'A moeda pode mudar até existir o primeiro item.',
        currencyLabel: 'Moeda',
        currencyLockedHint: 'A moeda fica travada depois que existe o primeiro item.',
        closeHint: 'Fecha a base da lista sem salvar.',
        finalize: 'Finalizar lista',
        finalizeHint: 'Desativado até a lista ter nome, orçamento e pelo menos um item planejado.',
        itemCount: '{{count}} itens planejados adicionados',
        itemsLabel: 'Itens planejados',
        itemsHint: 'Salvar e finalizar precisam de nome, orçamento e ao menos um item planejado.',
        nameHint: 'Dê um nome claro para a lista.',
        nameLabel: 'Nome da lista',
        namePlaceholder: 'Mantimentos da semana',
        save: 'Salvar rascunho',
        saveHint: 'Desativado até a lista ter nome, orçamento e pelo menos um item planejado.',
        summaryBudgetLabel: 'Prévia do orçamento',
        summaryCurrencyLabel: 'Moeda do rascunho',
        summaryItemsLabel: 'Itens planejados',
        summaryTitle: 'Rascunho atual',
        title: 'Criar lista',
      },
      plannedItem: {
        close: 'Fechar',
        editTitle: 'Editar item planejado',
        edit: 'Editar item',
        errors: {
          ambiguous: 'Use apenas um separador local.',
          empty: 'Digite um valor.',
          invalid: 'Use um número local válido.',
          nonPositive: 'O valor precisa ser maior que zero.',
          precision: 'Essa unidade não aceita tantas casas decimais.',
          unsafe: 'O valor é grande demais.',
        },
        nameHint: 'Use apenas o nome do produto.',
        nameLabel: 'Nome do item',
        namePlaceholder: 'Batatas',
        priceHint: 'Digite um preço localizado por unidade selecionada.',
        priceLabel: 'Preço planejado por {{unit}}',
        quantityHintFractional: 'Até 3 casas decimais para esta unidade.',
        quantityHintWhole: 'Apenas números inteiros para esta unidade.',
        quantityLabel: 'Quantidade',
        save: 'Salvar item',
        saveEdit: 'Salvar alterações',
        remove: 'Remover item',
        title: 'Item planejado',
        unitHint: 'Use apenas piece, pack, kg, g, l ou ml.',
        unitLabel: 'Unidade',
      },
      units: {
        g: 'g',
        kg: 'kg',
        l: 'l',
        ml: 'ml',
        pack: 'pacote',
        piece: 'peça',
      },
      form: {
        currencyLabel: 'Moeda',
        searchHelper: 'Estilizado por tokens semânticos, não por cores da tela.',
        searchLabel: 'Buscar',
        searchPlaceholder: 'Mantimentos do orçamento',
        openSheet: 'Abrir painel',
      },
      preferences: {
        currencyBrl: 'real brasileiro',
        currencySystem: 'Sistema',
        currencyUsd: 'dólar americano',
        languageSystem: 'Sistema',
      },
    },
  },
} as const;
