export const SUPPORTED_LANGUAGES = ['pt-BR', 'en'] as const;

export type SupportedLanguage = (typeof SUPPORTED_LANGUAGES)[number];

export const DEFAULT_LANGUAGE: SupportedLanguage = 'en';

export const localizationResources = {
  en: {
    translation: {
      app: {
        readyBody: 'Router, SQLite, and preferences are initialized.',
        readyTitle: 'Expo foundation ready',
        loading: 'Loading app shell…',
        error: 'Unable to start the app shell.',
        designPreviewBody: 'Semantic tokens, adapters, and theme resolution are wired up.',
        designPreviewTitle: 'Design system preview',
      },
      home: {
        activeSummaryBody: 'Open lists keep moving until they are finalized.',
        activeSummaryBudgetLabel: 'Budget',
        activeSummaryTitle: 'Active summaries',
        activeSummaryListsLabel: 'Lists',
        finalizedSummaryBody: 'Finished lists stay readable and can be reopened later.',
        finalizedSummaryBudgetLabel: 'Budget',
        finalizedSummaryListsLabel: 'Lists',
        finalizedSummaryTitle: 'Finalized summaries',
        subtitle: 'Plan the next list offline before you shop.',
        title: 'Home',
        openCreateList: 'Create list',
        openCreateListHint: 'Open the list shell to choose a currency and start planning.',
      },
      createList: {
        addItem: 'Add item',
        addItemHint: 'Adds one placeholder item so the list can be saved or finalized.',
        budgetHint: 'Use integer minor units for this shell.',
        budgetLabel: 'Budget',
        budgetPlaceholder: '4000',
        close: 'Close',
        clearItems: 'Clear items',
        clearItemsHint: 'Removes the placeholder items from the shell.',
        currencyHint: 'Currency can change until the first item exists.',
        currencyLabel: 'Currency',
        currencyLockedHint: 'Currency is locked after the first item exists.',
        closeHint: 'Dismiss the list shell without saving.',
        finalize: 'Finalize list',
        finalizeHint: 'Disabled until the list has a name, budget, and at least one item.',
        itemCount: '{{count}} items added',
        itemsLabel: 'Items',
        itemsHint: 'Save and finalize need a name, a budget, and at least one item.',
        nameHint: 'Give the list a clear name.',
        nameLabel: 'List name',
        namePlaceholder: 'Weekly groceries',
        save: 'Save draft',
        saveHint: 'Disabled until the list has a name, budget, and at least one item.',
        summaryBudgetLabel: 'Budget preview',
        summaryCurrencyLabel: 'Draft currency',
        summaryItemsLabel: 'Item count',
        summaryTitle: 'Current draft',
        title: 'Create list',
      },
      form: {
        currencyLabel: 'Currency',
        searchHelper: 'Styled by semantic tokens, not screen colors.',
        searchLabel: 'Search',
        searchPlaceholder: 'Budget groceries',
        openSheet: 'Open sheet',
      },
      preferences: {
        currencyBrl: 'Brazilian real',
        currencySystem: 'System',
        currencyUsd: 'US dollar',
        languageSystem: 'System',
      },
    },
  },
  'pt-BR': {
    translation: {
      app: {
        readyBody: 'Router, SQLite e preferências estão inicializados.',
        readyTitle: 'Base do Expo pronta',
        loading: 'Carregando a base do app…',
        error: 'Não foi possível iniciar a base do app.',
        designPreviewBody: 'Tokens semânticos, adapters e resolução de tema já estão conectados.',
        designPreviewTitle: 'Prévia do design system',
      },
      home: {
        activeSummaryBody: 'Listas abertas seguem em movimento até serem finalizadas.',
        activeSummaryBudgetLabel: 'Orçamento',
        activeSummaryTitle: 'Resumos ativos',
        activeSummaryListsLabel: 'Listas',
        finalizedSummaryBody: 'Listas finalizadas continuam legíveis e podem ser reabertas depois.',
        finalizedSummaryBudgetLabel: 'Orçamento',
        finalizedSummaryListsLabel: 'Listas',
        finalizedSummaryTitle: 'Resumos finalizados',
        subtitle: 'Planeje a próxima lista offline antes de comprar.',
        title: 'Início',
        openCreateList: 'Criar lista',
        openCreateListHint: 'Abre a base da lista para escolher a moeda e começar o planejamento.',
      },
      createList: {
        addItem: 'Adicionar item',
        addItemHint: 'Adiciona um item de apoio para que a lista possa ser salva ou finalizada.',
        budgetHint: 'Use valores inteiros em centavos neste shell.',
        budgetLabel: 'Orçamento',
        budgetPlaceholder: '4000',
        close: 'Fechar',
        clearItems: 'Limpar itens',
        clearItemsHint: 'Remove os itens de apoio da base.',
        currencyHint: 'A moeda pode mudar até existir o primeiro item.',
        currencyLabel: 'Moeda',
        currencyLockedHint: 'A moeda fica travada depois que existe o primeiro item.',
        closeHint: 'Fecha a base da lista sem salvar.',
        finalize: 'Finalizar lista',
        finalizeHint: 'Desativado até a lista ter nome, orçamento e pelo menos um item.',
        itemCount: '{{count}} itens adicionados',
        itemsLabel: 'Itens',
        itemsHint: 'Salvar e finalizar precisam de nome, orçamento e ao menos um item.',
        nameHint: 'Dê um nome claro para a lista.',
        nameLabel: 'Nome da lista',
        namePlaceholder: 'Mantimentos da semana',
        save: 'Salvar rascunho',
        saveHint: 'Desativado até a lista ter nome, orçamento e pelo menos um item.',
        summaryBudgetLabel: 'Prévia do orçamento',
        summaryCurrencyLabel: 'Moeda do rascunho',
        summaryItemsLabel: 'Quantidade de itens',
        summaryTitle: 'Rascunho atual',
        title: 'Criar lista',
      },
      form: {
        currencyLabel: 'Moeda',
        searchHelper: 'Estilizado por tokens semânticos, não por cores da tela.',
        searchLabel: 'Buscar',
        searchPlaceholder: 'Mantimentos do orçamento',
        openSheet: 'Abrir painel',
      },
      preferences: {
        currencyBrl: 'real brasileiro',
        currencySystem: 'Sistema',
        currencyUsd: 'dólar americano',
        languageSystem: 'Sistema',
      },
    },
  },
} as const;
